Starting to use raywenderlich/swift-style-guide
rubenglobant/INActors pull request #2
Opened 2017-09-21 15:08 UTC by rubenglobant

started to work with swift style guide

2017-09-21 15:11 UTC, rubenglobant reviewed
starting point for swift style into this project

2017-10-24 15:04 UTC, jsamboni requested changes
A couple of changes to be made before merging but overall looks nice!

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsDescriptionViewController.swift
> +
This linebreak can be deleted

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsDescriptionViewController.swift
> +
All these linebreaks should be deleted

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
> +
extra linebreak can be deleted

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
> +
extra line break should be deleted

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
> +
extra line break should be deleted

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
> +
This line break can be deleted

2017-10-24 15:04 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
>          name = actor?["name"] as? NSString
i believe we can use String here instead of NSString

2017-11-02 14:53 UTC, jsamboni approved these changes
looks much better!

2017-12-21 16:07 UTC, merged

2017-12-21 16:08 UTC, rubenglobant commented
changes merged