Added contraints V2
rubenglobant/INActors pull request #3
Opened 2017-10-20 21:58 UTC by rubenglobant

2017-10-20 21:59 UTC, rubenglobant commented
added constraints according Juan Carlos suggestions

2017-10-24 15:08 UTC, jsamboni requested changes
Some minor changes to be made, but the constraints looks good!

2017-10-24 15:08 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
> +//    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
if we're not using this, we should delete it

2017-10-24 15:08 UTC, jsamboni commented on INActors/ActorsTableViewController.swift
> +
extra line break should be deleted

2017-11-02 14:52 UTC, jsamboni approved these changes
Looks nice!

2017-12-21 16:01 UTC, merged

2017-12-21 16:01 UTC, rubenglobant commented
merge 1